// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8lz6WeGdl3LXybPu4Fx5nWfm00VfqAPM',
    appId: '1:696677786251:web:059ed0f59f053a5b236a8e',
    messagingSenderId: '696677786251',
    projectId: 'parking-management-2dd20',
    authDomain: 'parking-management-2dd20.firebaseapp.com',
    storageBucket: 'parking-management-2dd20.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWU-XukgHrarFagF_ECJOostPK5fBkDX0',
    appId: '1:696677786251:android:37eef547ad0386c6236a8e',
    messagingSenderId: '696677786251',
    projectId: 'parking-management-2dd20',
    storageBucket: 'parking-management-2dd20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaNFXp0Nk-fN5z-EGcbYtRoZLZC8zzChg',
    appId: '1:696677786251:ios:ec0b0d3d93e9445f236a8e',
    messagingSenderId: '696677786251',
    projectId: 'parking-management-2dd20',
    storageBucket: 'parking-management-2dd20.firebasestorage.app',
    iosBundleId: 'com.example.parkingManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaNFXp0Nk-fN5z-EGcbYtRoZLZC8zzChg',
    appId: '1:696677786251:ios:ec0b0d3d93e9445f236a8e',
    messagingSenderId: '696677786251',
    projectId: 'parking-management-2dd20',
    storageBucket: 'parking-management-2dd20.firebasestorage.app',
    iosBundleId: 'com.example.parkingManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8lz6WeGdl3LXybPu4Fx5nWfm00VfqAPM',
    appId: '1:696677786251:web:1624474f0b4f54d2236a8e',
    messagingSenderId: '696677786251',
    projectId: 'parking-management-2dd20',
    authDomain: 'parking-management-2dd20.firebaseapp.com',
    storageBucket: 'parking-management-2dd20.firebasestorage.app',
  );
}
