// File generated by FlutterFire CLI.
// ---------------------------------------------------------------------------
// THIS IS A PLACEHOLDER. Do not use these values as-is.
//
// Generate the real version of this file by running, from the mobile-app/
// folder, after installing the FlutterFire CLI (see docs/SETUP_GUIDE.md):
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// That command will connect to your Firebase project, let you pick which
// platforms to support (Android/iOS/Web), and overwrite this file with your
// project's real API keys and app IDs. It also registers the Android/iOS
// apps in Firebase automatically and drops the platform config files
// (google-services.json / GoogleService-Info.plist) into the right folders.
// ---------------------------------------------------------------------------

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - run `flutterfire configure`.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform - run `flutterfire configure`.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME.appspot.com',
    iosBundleId: 'com.example.parkingManager',
  );
}
